### ISSUE TITLE
Publish on pypi ?

### ISSUE THREAD

**Issue by aestrivex** [pmneila/PyMCubes#1]
Hello,

Your implementation of the marching cubes algorithm does a better job than the one in scikit-image which seems consistently to leave holes in the surface. There is another implementation called pythonisosurfaces which uses javascript and is much less easy to call from within python.

Would you consider publishing your implementation on pypi so I can depend on it more easily? I am not asking out of licensing issues, my software is also GPL, but just for ease of distribution.

**Comment by aestrivex** [comment]
Hello, 

since you have not responded and your software is licensed GPL, I am going to publish it on pypi. I will therefore be the maintainer but I am happy to transfer this responsibility to you in the future.

**Comment by pmneila** [comment]
Hi,

PyMCubes is now on PyPI.
