### ISSUE TITLE
PyMCubes version compatible with Python 2.7

### ISSUE THREAD

**Issue by SparshJ** [pmneila/PyMCubes#18]
Hey!
I am trying to install a pipeline (IELU Master GitHub) that is written in python 2.7. It is dependent on PyMCubes. Is there a way to obtain a python 2.7 version of your project so that I can use it?

Right now the main error I get is because of the super function (zero arguments provided in python 3.x)

Thanks!

**Comment by pmneila** [comment]
Hi,

It should be fixed now. Try installing the version 0.0.9 (`pip install --upgrade PyMCubes` should work).

Sorry for the inconvenience.
