### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by zimka** [pmneila/PyMCubes#2]
Got an error when tried to build: 
"error: command 'C:\\Users\\zimka\\AppData\\Local\\Programs\\Common\\Microsoft\\V
isual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2"
The same thing with pip install

Full text of errors:
>python setup.py build
running build
running build_py
running build_ext
building 'mcubes._mcubes' extension
C:\Users\zimka\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0
\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\lib\site-packa
ges\numpy\core\include -IC:\Python27\include -IC:\Python27\PC /Tpmcubes/src/_mcu
bes.cpp /Fobuild\temp.win32-2.7\Release\mcubes/src/_mcubes.obj
_mcubes.cpp
c:\python27\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(
12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DE
PRECATED_API NPY_1_7_API_VERSION
C:\Users\zimka\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0
\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind
 semantics are not enabled. Specify /EHsc
C:\Users\zimka\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0
\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\lib\site-packa
ges\numpy\core\include -IC:\Python27\include -IC:\Python27\PC /Tpmcubes/src/pywr
apper.cpp /Fobuild\temp.win32-2.7\Release\mcubes/src/pywrapper.obj
pywrapper.cpp
c:\python27\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(
12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DE
PRECATED_API NPY_1_7_API_VERSION
C:\Users\zimka\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0
\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind
 semantics are not enabled. Specify /EHsc
c:\pymcubes\mcubes\src\marchingcubes.h(29) : error C4430: missing type specifier
 - int assumed. Note: C++ does not support default-int
        mcubes/src/pywrapper.cpp(58) : see reference to function template instan
tiation 'void mc::marching_cubes<double[3],PythonToCFunc>(const vector3 (&),cons
t vector3 (&),int,int,int,formula,double,std::vector<_Ty> &,std::vector<int> &)'
 being compiled
        with
        [
            vector3=double [3],
            formula=PythonToCFunc,
            _Ty=double
        ]
c:\pymcubes\mcubes\src\marchingcubes.h(29) : error C2513: 'int' : no variable de
clared before '='
c:\pymcubes\mcubes\src\marchingcubes.h(29) : error C2146: syntax error : missing
 ';' before identifier 'coord_type'
c:\pymcubes\mcubes\src\marchingcubes.h(29) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(34) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(34) : error C2146: syntax error : missing
 ';' before identifier 'dx'
c:\pymcubes\mcubes\src\marchingcubes.h(34) : error C2065: 'dx' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(34) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(35) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(35) : error C2146: syntax error : missing
 ';' before identifier 'dy'
c:\pymcubes\mcubes\src\marchingcubes.h(35) : error C2065: 'dy' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(35) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(36) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(36) : error C2146: syntax error : missing
 ';' before identifier 'dz'
c:\pymcubes\mcubes\src\marchingcubes.h(36) : error C2065: 'dz' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(36) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(44) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(44) : error C2146: syntax error : missing
 ';' before identifier 'x'
c:\pymcubes\mcubes\src\marchingcubes.h(44) : error C2065: 'x' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(44) : error C2065: 'dx' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(45) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(45) : error C2146: syntax error : missing
 ';' before identifier 'x_dx'
c:\pymcubes\mcubes\src\marchingcubes.h(45) : error C2065: 'x_dx' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(45) : error C2065: 'dx' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(48) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(48) : error C2146: syntax error : missing
 ';' before identifier 'y'
c:\pymcubes\mcubes\src\marchingcubes.h(48) : error C2065: 'y' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(48) : error C2065: 'dy' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(49) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(49) : error C2146: syntax error : missing
 ';' before identifier 'y_dy'
c:\pymcubes\mcubes\src\marchingcubes.h(49) : error C2065: 'y_dy' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(49) : error C2065: 'dy' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(52) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(52) : error C2146: syntax error : missing
 ';' before identifier 'z'
c:\pymcubes\mcubes\src\marchingcubes.h(52) : error C2065: 'z' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(52) : error C2065: 'dz' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(53) : error C2065: 'coord_type' : undecla
red identifier
c:\pymcubes\mcubes\src\marchingcubes.h(53) : error C2146: syntax error : missing
 ';' before identifier 'z_dz'
c:\pymcubes\mcubes\src\marchingcubes.h(53) : error C2065: 'z_dz' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(53) : error C2065: 'dz' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(56) : error C2065: 'x' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(56) : error C2065: 'y' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(56) : error C2065: 'z' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(56) : error C2065: 'x_dx' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(56) : error C2065: 'y' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(56) : error C2065: 'z' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(57) : error C2065: 'x_dx' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(57) : error C2065: 'y_dy' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(57) : error C2065: 'z' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(57) : error C2065: 'x' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(57) : error C2065: 'y_dy' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(57) : error C2065: 'z' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(58) : error C2065: 'x' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(58) : error C2065: 'y' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(58) : error C2065: 'z_dz' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(58) : error C2065: 'x_dx' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(58) : error C2065: 'y' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(58) : error C2065: 'z_dz' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(59) : error C2065: 'x_dx' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(59) : error C2065: 'y_dy' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(59) : error C2065: 'z_dz' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(59) : error C2065: 'x' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(59) : error C2065: 'y_dy' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(59) : error C2065: 'z_dz' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(74) : error C2065: 'x_dx' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(74) : error C2065: 'y_dy' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(74) : error C2065: 'z_dz' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(74) : error C2065: 'x' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(80) : error C2065: 'x_dx' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(80) : error C2065: 'y' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(80) : error C2065: 'z_dz' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(80) : error C2065: 'y_dy' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(86) : error C2065: 'x_dx' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(86) : error C2065: 'y' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(86) : error C2065: 'dx' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(86) : error C2065: 'z' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(86) : error C2065: 'z_dz' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(94) : error C2065: 'x' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(94) : error C2065: 'y' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(94) : error C2065: 'z' : undeclared ident
ifier
c:\pymcubes\mcubes\src\marchingcubes.h(94) : error C2065: 'x_dx' : undeclared id
entifier
c:\pymcubes\mcubes\src\marchingcubes.h(104) : error C2065: 'x_dx' : undeclared i
dentifier
c:\pymcubes\mcubes\src\marchingcubes.h(104) : error C2065: 'y' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(104) : error C2065: 'z' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(104) : error C2065: 'y_dy' : undeclared i
dentifier
c:\pymcubes\mcubes\src\marchingcubes.h(114) : error C2065: 'x_dx' : undeclared i
dentifier
c:\pymcubes\mcubes\src\marchingcubes.h(114) : error C2065: 'y_dy' : undeclared i
dentifier
c:\pymcubes\mcubes\src\marchingcubes.h(114) : error C2065: 'z' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(114) : error C2065: 'x' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(124) : error C2065: 'x' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(124) : error C2065: 'y_dy' : undeclared i
dentifier
c:\pymcubes\mcubes\src\marchingcubes.h(124) : error C2065: 'z' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(124) : error C2065: 'y' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(134) : error C2065: 'x' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(134) : error C2065: 'y' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(134) : error C2065: 'z_dz' : undeclared i
dentifier
c:\pymcubes\mcubes\src\marchingcubes.h(134) : error C2065: 'x_dx' : undeclared i
dentifier
c:\pymcubes\mcubes\src\marchingcubes.h(144) : error C2065: 'x' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(144) : error C2065: 'y_dy' : undeclared i
dentifier
c:\pymcubes\mcubes\src\marchingcubes.h(144) : error C2065: 'z_dz' : undeclared i
dentifier
c:\pymcubes\mcubes\src\marchingcubes.h(144) : error C2065: 'y' : undeclared iden
tifier
c:\pymcubes\mcubes\src\marchingcubes.h(144) : fatal error C1003: error count exc
eeds 100; stopping compilation
error: command 'C:\\Users\\zimka\\AppData\\Local\\Programs\\Common\\Microsoft\\V
isual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

**Comment by pmneila** [comment]
Hi,

I just pushed a fix to your problem. Unfortunately, I don't have a Windows to check if it works. Could you try it and let me know if you find any problem?

**Comment by zimka** [comment]
Hello. I'm sorry but it looks like this fix is not enough, there are still errors during the compilation. Anyway errors list have been changed:

C:\Users\zimka\Desktop\PyMCubes-master>python setup.py build
running build
running build_py
running build_ext
building 'mcubes._mcubes' extension
C:\Users\zimka\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0
\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\lib\site-packa
ges\numpy\core\include -IC:\Python27\include -IC:\Python27\PC /Tpmcubes/src/_mcu
bes.cpp /Fobuild\temp.win32-2.7\Release\mcubes/src/_mcubes.obj -std=c++11
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
_mcubes.cpp
c:\python27\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(
12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DE
PRECATED_API NPY_1_7_API_VERSION
C:\Users\zimka\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0
\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind
 semantics are not enabled. Specify /EHsc
C:\Users\zimka\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0
\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\lib\site-packa
ges\numpy\core\include -IC:\Python27\include -IC:\Python27\PC /Tpmcubes/src/pywr
apper.cpp /Fobuild\temp.win32-2.7\Release\mcubes/src/pywrapper.obj -std=c++11
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
pywrapper.cpp
c:\python27\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(
12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DE
PRECATED_API NPY_1_7_API_VERSION
C:\Users\zimka\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0
\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind
 semantics are not enabled. Specify /EHsc
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(29) : error C4
430: missing type specifier - int assumed. Note: C++ does not support default-in
t
        mcubes/src/pywrapper.cpp(58) : see reference to function template instan
tiation 'void mc::marching_cubes<double[3],PythonToCFunc>(const vector3 (&),cons
t vector3 (&),int,int,int,formula,double,std::vector<_Ty> &,std::vector<int> &)'
 being compiled
        with
        [
            vector3=double [3],
            formula=PythonToCFunc,
            _Ty=double
        ]
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(29) : error C2
513: 'int' : no variable declared before '='
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(29) : error C2
146: syntax error : missing ';' before identifier 'coord_type'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(29) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(34) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(34) : error C2
146: syntax error : missing ';' before identifier 'dx'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(34) : error C2
065: 'dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(34) : error C2
061: syntax error : identifier 'coord_type'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(35) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(35) : error C2
146: syntax error : missing ';' before identifier 'dy'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(35) : error C2
065: 'dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(35) : error C2
061: syntax error : identifier 'coord_type'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(36) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(36) : error C2
146: syntax error : missing ';' before identifier 'dz'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(36) : error C2
065: 'dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(36) : error C2
061: syntax error : identifier 'coord_type'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(44) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(44) : error C2
146: syntax error : missing ';' before identifier 'x'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(44) : error C2
065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(44) : error C2
065: 'dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(45) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(45) : error C2
146: syntax error : missing ';' before identifier 'x_dx'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(45) : error C2
065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(45) : error C2
065: 'dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(48) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(48) : error C2
146: syntax error : missing ';' before identifier 'y'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(48) : error C2
065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(48) : error C2
065: 'dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(49) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(49) : error C2
146: syntax error : missing ';' before identifier 'y_dy'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(49) : error C2
065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(49) : error C2
065: 'dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(52) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(52) : error C2
146: syntax error : missing ';' before identifier 'z'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(52) : error C2
065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(52) : error C2
065: 'dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(53) : error C2
065: 'coord_type' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(53) : error C2
146: syntax error : missing ';' before identifier 'z_dz'
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(53) : error C2
065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(53) : error C2
065: 'dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(56) : error C2
065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(56) : error C2
065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(56) : error C2
065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(56) : error C2
065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(56) : error C2
065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(56) : error C2
065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(57) : error C2
065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(57) : error C2
065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(57) : error C2
065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(57) : error C2
065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(57) : error C2
065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(57) : error C2
065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(58) : error C2
065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(58) : error C2
065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(58) : error C2
065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(58) : error C2
065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(58) : error C2
065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(58) : error C2
065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(59) : error C2
065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(59) : error C2
065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(59) : error C2
065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(59) : error C2
065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(59) : error C2
065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(59) : error C2
065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(74) : error C2
065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(74) : error C2
065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(74) : error C2
065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(74) : error C2
065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(80) : error C2
065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(80) : error C2
065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(80) : error C2
065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(80) : error C2
065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(86) : error C2
065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(86) : error C2
065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(86) : error C2
065: 'dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(86) : error C2
065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(86) : error C2
065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(94) : error C2
065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(94) : error C2
065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(94) : error C2
065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(94) : error C2
065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(104) : error C
2065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(104) : error C
2065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(104) : error C
2065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(104) : error C
2065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(114) : error C
2065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(114) : error C
2065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(114) : error C
2065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(114) : error C
2065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(124) : error C
2065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(124) : error C
2065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(124) : error C
2065: 'z' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(124) : error C
2065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(134) : error C
2065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(134) : error C
2065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(134) : error C
2065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(134) : error C
2065: 'x_dx' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(144) : error C
2065: 'x' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(144) : error C
2065: 'y_dy' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(144) : error C
2065: 'z_dz' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(144) : error C
2065: 'y' : undeclared identifier
c:\users\zimka\desktop\pymcubes-master\mcubes\src\marchingcubes.h(144) : fatal e
rror C1003: error count exceeds 100; stopping compilation
error: command 'C:\\Users\\zimka\\AppData\\Local\\Programs\\Common\\Microsoft\\V
isual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

**Comment by pmneila** [comment]
Hi, zimka,

Sorry for the inconvenience. Unfortunately I'm very busy these weeks and I don't have a Windows machine with Visual C++ readily available. I'll take a look at it in 3-4 weeks. In the meantime you can get the code working if you change the line 25 of `marchingcubes.h`:
```c++
typedef decltype(lower[0]) coord_type;
```
by
```c++
typedef double coord_type;
```
Then run `python setup.py build` again and it should work. Let me know otherwise.

**Comment by pmneila** [comment]
Hi,

I finally could install Windows and fix the problem. I uploaded the new version to PyPI, so you should be able to install it via
```
pip install PyMCubes
```

Again, let me know if you get any error.

**Comment by zimka** [comment]
Hello,
It looks like everything is alright now.
Thank you for maintaining.
