### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ravidraj10** [pmneila/PyMCubes#21]
Unable to install PyMCubes via pip. While installation it says "error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/"
I already installed the tool still facing the same issue.
![Screenshot (11)](https://user-images.githubusercontent.com/41807473/62472222-3da3b280-b76c-11e9-8816-34345b9d5bf0.png)

**Comment by pmneila** [comment]
If you keep getting the same error it is very likely that you didn't install some required packages from the Visual C++ Build Tools. Check that you installed the packages mentioned in [this short tutorial](https://www.scivision.dev/python-windows-visual-c-14-required/).

In any case, I just uploaded a Python wheel for `PyMCubes` to the PyPI repository. That means that you can install a pre-compiled binary version of PyMCubes for Windows by running ```pip install PyMCubes``` (or ```pip install PyMCubes --no-cache-dir``` to avoid compiling the already downloaded source package). This will install the binary package (no compilation required) if you have a setup compatible with the wheel.

**Comment by bharadwajdhornala** [comment]
Hi @pmneila @ravidraj10 I am working on my research and needed PyMCubes for fine outputs. I get the same error as @ravidraj10 . I have tried installing using pip install PyMCubes --no-cache-dir, it gives an error **no such option: --no-chache-dir**. How should I proceed further?

**Comment by pmneila** [comment]
Hi @bharadwajdhornala 

I uploaded a wheel for Windows to PyPI. It should work now.

> it gives an error no such option: --no-chache-dir

It looks like a typo. You wrote `chache`. It is `cache`.

**Comment by bharadwajdhornala** [comment]
Hi @pmneila Will it work only when I install Microsoft Visual C++ 14.0? Can it work with any version.

**Comment by pmneila** [comment]
No, now it should work without MSVC++. I uploaded a precomplied binary. You should get it with
```
pip install PyMCubes --no-cache-dir
```

**Comment by bharadwajdhornala** [comment]
I have tried to install using pip install PyMCubes --no-cache-dir . It gives the same error--Microsoft Visual C++ needed

**Comment by pmneila** [comment]
What Windows version do you have? Is it 32- or 64-bit? The precompiled binary is 64-bit only.

Can you copy the entire output of `pip install PyMCube --no-cache-dir`?

**Comment by bharadwajdhornala** [comment]
It is 64-bit. Output the command gave
C:\>pip install PyMCubes --no-cache-dir
Collecting PyMCubes
  Downloading https://files.pythonhosted.org/packages/39/ef/610b4663f6be276f7dafcd762a300fd7b93aea6ae1ad706438c35a6d922c/PyMCubes-0.1.0.tar.gz (42kB)
    100% |################################| 51kB 5.7MB/s
Installing collected packages: PyMCubes
  Running setup.py install for PyMCubes ... error
    Complete output from command C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\IM_NET\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DHORNA~1.BHA\\AppData\\Local\\Temp\\pip-install-qko10_2l\\PyMCubes\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DHORNA~1.BHA\AppData\Local\Temp\pip-record-sfhcid0_\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\mcubes
    copying mcubes\exporter.py -> build\lib.win-amd64-3.5\mcubes
    copying mcubes\smoothing.py -> build\lib.win-amd64-3.5\mcubes
    copying mcubes\torch_smoothing.py -> build\lib.win-amd64-3.5\mcubes
    copying mcubes\__init__.py -> build\lib.win-amd64-3.5\mcubes
    running build_ext
    building 'mcubes._mcubes' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

**Comment by pmneila** [comment]
Hi @bharadwajdhornala 

I think I see the problem. The wheel has been compiled for Python 3.7, but from your log it seems you are using Python 3.5. Would it be possible for you to update your Python to version 3.7? Otherwise, you will need to install MSVC++ or wait until I build the package for Python 3.5 (which might take some time).

**Comment by fewerjunk** [comment]
Blender 2.9 Sverchok Extra Nodes install PyMCubes (geomdl as well) points to this website.

Install succeeds, under Python3.8

Followup on install is that Blender uses Python3.7

Do I need to switch install to Python3.7?  If so, how?

If not, it shows installed but, is not recognized by Blender 2.9 (MacOS - Catalina).

**Comment by Kunal-sanjay-saxena** [comment]
Processing c:\users\kunal saxena\stable-dreamfusion\pymcubes
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\anaconda\envs\modelling\lib\site-packages (from PyMCubes==0.1.4) (1.21.6)
Requirement already satisfied: scipy>=1.0.0 in c:\anaconda\envs\modelling\lib\site-packages (from PyMCubes==0.1.4) (1.7.3)
Building wheels for collected packages: PyMCubes
  Building wheel for PyMCubes (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for PyMCubes (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'mcubes._mcubes' extension
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Imcubes/src -IC:\Users\KUNALS~1\AppData\Local\Temp\pip-build-env-421uo1n9\overlay\Lib\site-packages\numpy\core\include -IC:\Anaconda\envs\modelling\include -IC:\Anaconda\envs\modelling\Include /EHsc /Tpmcubes/src/_mcubes.cpp /Fobuild\temp.win-amd64-cpython-37\Release\mcubes/src/_mcubes.obj -std=c++11 -Wall
      error: command 'cl.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyMCubes
Failed to build PyMCubes
ERROR: Could not build wheels for PyMCubes, which is required to install pyproject.toml-based projects

**Comment by pmneila** [comment]
Hi @Kunal-sanjay-saxena 

What command did you run to get that error message? In principle you should not need to compile PyMCubes, as there are wheels available when installing it with `pip install PyMCubes`.
