### ISSUE TITLE
Multimaterial Capability?

### ISSUE THREAD

**Issue by jonathanhestroffer** [pmneila/PyMCubes#25]
Hi,

I have volume data consisting of different materials with different Feature Ids.

Will PyMCubes work for this type of multimaterial data? For example I would like the isosurface for each Feature Id.

Many thanks,
Jonathan

**Comment by pmneila** [comment]
Hi @jonathanhestroffer 

Not sure if I understand what you need. How is exactly your volume data? You have an array indicating different regions of your the volume and need to assign indices to the vertices? You need to extract multiple isosurfaces, one per feature id? What are these feature ids?

Do you have a minimal piece of code that exemplifies your problem?

**Comment by jonathanhestroffer** [comment]
Hi,

[image: image.png]

This is the type of volumetric data I am working with. Each color
represents a Feature with a certain ID. I would like to perform the
marching cubes algorithm and extract an isosurface for each Feature.
Feature IDs are simply unique integer numbers from 1 to the total number of
Features. For example, let's say the red Feature (bottom of the example
volume) has an ID of 1, then I would like to extract the isosurface for
value 1.

I hope this helps clarify

**Comment by pmneila** [comment]
Hi, 

I cannot see the image. Do you have a link?

In any case, if I understood correctly, cannot you just run marching cubes once per isosurface? Something like this:
```Python
meshes = [mcubes.marching_cubes(volume, fid) for fid in feature_ids]
```
Would that solve your problem?

**Comment by jonathanhestroffer** [comment]
![image](https://user-images.githubusercontent.com/55960462/78958748-de860280-7a9d-11ea-8ed9-6c8c89b0cf63.png)

Here is the image.

I forgot to mention that I haven't yet tried your code :)

I will try this. Thank you!

**Comment by pmneila** [comment]
I see. After seeing your image I realize that my first impression was not correct. What you want is to extract the mesh surrounding each feature id? In that case, the code you want might be like this:
```Python
meshes = [mcubes.marching_cubes(volume == fid, 0.5) for fid in feature_ids]
```

Let me know if that works.
