### ISSUE TITLE
Broken Mesh

### ISSUE THREAD

**Issue by YoruCathy** [pmneila/PyMCubes#27]
Hello, I am trying to covert voxel to mesh with marching cubes.
My code is as the following 
```voxel = mcubes.smooth(vox, method='auto')  
vertices, triangles = mcubes.marching_cubes(voxel, 0.5)  
mcubes.export_mesh(vertices, triangles, "gorira.obj", "gorira")  
print("Plotting mesh...")  
mlab.triangular_mesh(
    vertices[:, 0], vertices[:, 1], vertices[:, 2], triangles)
print("Done.")  
mlab.show()
```

The `voxel` is visualized as
![image](https://user-images.githubusercontent.com/16759982/88886463-1f806d80-d26d-11ea-8e93-f60da6d8285a.png)
However, after marching cubes algorithm, it becomes broken, like this

![image](https://user-images.githubusercontent.com/16759982/88886575-56ef1a00-d26d-11ea-95d8-a56cdf0069d2.png)

Why does this happen? Does anyone have some ideas about this?

**Comment by pmneila** [comment]
Hi @YoruCathy,

Without having access to the `voxel` array and without knowing its internal structure, it is hard to answer your question. My first suggestion is to chage the value of the extracted isosurface to 0:

```Python
vertices, triangles = mcubes.marching_cubes(voxel, 0)
```

If that does not solve your problem, could you send me an example `voxel` array?

**Comment by YoruCathy** [comment]
Thanks to your suggestion, I tried this solution but it still doesn't work.
The voxel file is uploaded on Google Drive [here](https://drive.google.com/file/d/1zyX2MTGIwu8KghZbUh7J_EEVKn4Ld3rm/view?usp=sharing)

**Comment by pmneila** [comment]
Hi,

I think I understand your problem now. This _broken mesh_ is expected behavior, since the 0.5 isosurface touches the boder of the array. If you want that your mesh is _closed_, you can simply pad your array with zeros in all dimensions. Something like this should work:

```python
voxel = np.pad(voxel, 1)
vertices, triangles = mcubes.marching_cubes(voxel, 0.5)  
mcubes.export_mesh(vertices, triangles, "gorira.obj", "gorira")  
```

Note that, since the version 0.1 of `PyMCubes` it is possible to smooth the embedding array to produce better results. For example
```python
voxel = np.pad(voxel, 1)
voxel = mcubes.smooth(voxel)
vertices, triangles = mcubes.marching_cubes(voxel, 0)  # If you smooth the array you need to extract the 0-isosurface
mcubes.export_mesh(vertices, triangles, "gorira.obj", "gorira")  
```

Hope that helps.
