### ISSUE TITLE
Fails to compile on linux

### ISSUE THREAD

**Issue by andrewdalecramer** [pmneila/PyMCubes#3]
Tried to compile on linux (redhat), log is at http://pastebin.com/WrgAJBsm

gcc version 4.8.1 20130715 (Red Hat 4.8.1-4) (GCC)

**Comment by pmneila** [comment]
Hi,

I pushed a fix. It should be working now. Sorry for the inconvenience.

**Comment by choldgraf** [comment]
Same here - seemed to be some sort of error being thrown in numpy. Error dump [here](http://pastebin.com/pj9fXeu3)

**Comment by andrewdalecramer** [comment]
Excellent, compiles fine.

**Comment by pmneila** [comment]
@andrewdalecramer That's great.

@choldgraf That's strange. The error is in one of the header files of your system (`/usr/include/bits/stdio.h`), not in the code of PyMCubes itself. I will take a look at it later.

**Comment by choldgraf** [comment]
Ah ok - maybe it's on my end then? Unfortunately this is on a cluster for
which I don't have full control of the environment, but I'll see what I can
do on my end to make it work.

**Comment by andrewdalecramer** [comment]
Compilers are a pain, check the version on your cluster as it might just be too old. I had to petition quite a bit to get an updated compiler on our system that was younger than 6 years old.

**Comment by pmneila** [comment]
@choldgraf Take a took at https://gcc.gnu.org/ml/gcc-help/2013-07/msg00127.html and the follow-ups. They are talking about the same error you are having. According to them, the error disappears using a different version of gcc (or removing the -Ox optimization flags, but I don't think that's a valid solution). Do you have any other version of gcc installed on that cluster?

**Comment by choldgraf** [comment]
Thanks for tracking that down for me. Updating to the latest gcc did in fact solve the problem, so pymcubes is now compiled :)

**Comment by pmneila** [comment]
Great!

I close the issue then.
