### ISSUE TITLE
 ModuleNotFoundError: No module named 'mcubes._mcubes'

### ISSUE THREAD

**Issue by trendysloth** [pmneila/PyMCubes#34]
Got the following error 

**import mcubes**
      1 
----> 2 from ._mcubes import marching_cubes, marching_cubes_func
      3 from .exporter import export_mesh, export_obj, export_off
      4 from .smoothing import *

**ModuleNotFoundError: No module named 'mcubes._mcubes'**

installed through pip3 install pymcubes
system: ubuntu 20.04

**Comment by xanderseren** [comment]
Getting the same error, @trendysloth any chance you resolved this?

**Comment by pmneila** [comment]
Hi,

I have just released a new version of PyMCubes that includes a wide range of pre-compiled packages. This should allow you to install the package on your platform without the need to compile it from the source and hopefully avoid this kind of problems. To install it, use the following command:
```bash
python -m pip install --upgrade PyMCubes --no-cache-dir
```
I hope this resolves the issue for you, but in case the problem persists, please open a new issue.

Best
