### ISSUE TITLE
Failed to find exporter after installation

### ISSUE THREAD

**Issue by andrewdalecramer** [pmneila/PyMCubes#4]
Hey, got it to compile and install but still doesn't run

Traceback (most recent call last):
  File "generate.py", line 6, in <module>
    import mcubes
  File "/home/user/local/anaconda3/lib/python3.4/site-packages/PyMCubes-0.0.4-py3.4-linux-x86_64.egg/mcubes/__init__.py", line 3, in <module>
    from exporter import export_mesh
ImportError: No module named 'exporter'

**Comment by pmneila** [comment]
Sorry, the library was developed and tested for Python 2, not Python 3. I'll fix that soon. In the meantime, you can just edit the file `/home/user/local/anaconda3/lib/python3.4/site-packages/PyMCubes-0.0.4-py3.4-linux-x86_64.egg/mcubes/init.py` and change the last line to

```Python
from .exporter import export_mesh
```
(note the extra dot before `exporter`). That should make it work.

**Comment by andrewdalecramer** [comment]
Ahhh, makes sense. Thanks for the support you've provided, I've ended up putting it into matlab and using isosurface now so don't stress too much.

**Comment by pmneila** [comment]
Hi,

I pushed some changes to make the library compatible with Python 2 and 3 and uploaded the new version to PyPI. All your problems should be fixed now.
