### ISSUE TITLE
[Feature] Add to conda-forge

### ISSUE THREAD

**Issue by willGraham01** [pmneila/PyMCubes#44]
Hi @pmneila,

We depend on `PyMCubes` in our [`brainglobe-atlasapi`](https://github.com/brainglobe/brainglobe-atlasapi) package, which we're looking to put onto `conda-forge`.

`conda-forge` doesn't let us add packages unless all dependencies are available through `conda-forge` itself, so I wanted to ask if you would be OK with us writing the recipe and making PyMCubes available through `conda`. We would be happy to add you as a maintainer to the resulting `conda` package too, of course.

Thanks,
Will (@willGraham01)

**Comment by pmneila** [comment]
Hi, @willGraham01,

Sure! Feel free to write the recipe for conda. That would be very helpful, actually.

Keep me updated and let me know if you need any help.

Best

**Comment by willGraham01** [comment]
Fab, thanks @pmneila - we have a working conda-forge recipe and have added you as a maintainer.

If you could drop a comment on this PR: https://github.com/conda-forge/staged-recipes/pull/25533 confirming that you're happy to be a maintainer, we can get it reviewed and onto conda-forge. :smile: 

By default conda-forge also includes me as a maintainer, but if you'd like to be the sole owner just let me know.

**Comment by willGraham01** [comment]
@pmneila We've requested review on https://github.com/conda-forge/staged-recipes/pull/25533 so `PyMCubes` will have a feedstock generated soon.

If you want to be given maintainer access on the conda-forge feedstock, let us know! (The linked PR is set to close this issue once merged).

**Comment by pmneila** [comment]
Hey, @willGraham01 ,

Thank you for taking care of this. I just left a comment on the PR; hopefully, it's not too late. Past couple of weeks have been quite hectic for me. Also, I'm totally fine with you being a co-maintainer, especially given my limited availability lately.

Best

**Comment by willGraham01** [comment]
Closing with the merge of https://github.com/conda-forge/pymcubes-feedstock :partying_face:
